{{- if .Values.global.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-stack.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sentinel-stack.labels" . | nindent 4 }}
